export const ROUTES = {
  HOME: '/',
  RENT: '/rent',
  BUY: '/buy',
  SELL: '/sell',
  BOOKING: '/booking',
  ABOUT: '/about',
  CONTACT: '/contact',
  LOGIN: '/login',
  REGISTER: '/register',
  PROFILE: '/profile',
  UNAUTHORIZED: '/unauthorized',
  ADMIN: {
    DASHBOARD: '/admin/dashboard',
    CARS: '/admin/cars',
    BOOKINGS: '/admin/bookings',
    SELL_REQUESTS: '/admin/sell-requests',
    USERS: '/admin/users',
    ANALYTICS: '/admin/analytics',
    FEATURED: '/admin/featured',
    REVIEWS: '/admin/reviews',
    NOTIFICATIONS: '/admin/notifications',
    SETTINGS: '/admin/settings',
  },
};
