// DriveHub Dummy Data

export const rentalCars = [
  {
    id: "r1",
    name: "Porsche 911 Carrera S",
    brand: "Porsche",
    category: "Sports",
    rating: 4.9,
    reviewsCount: 142,
    seats: 4,
    fuel: "Petrol",
    transmission: "Automatic",
    pricePerDay: 55000,
    images: [
      "https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80",
      // "https://images.unsplash.com/photo-1611245801484-96317d5a9005?auto=format&fit=crop&w=800&q=80"
    ],
    features: ["GPS Navigation", "Bose Audio", "Leather Seats", "Adaptive Cruise Control", "Apple CarPlay", "Heated Seats"],
    engine: "3.0L Twin-Turbo Flat-6",
    power: "443 HP",
    acceleration: "3.5s (0-60 mph)",
    description: "Experience the timeless legacy of the Porsche 911 Carrera S. Boasting a precision-tuned 3.0L Twin-Turbo flat-six engine, it delivers unmatched handling and raw performance that makes every road feel like a racetrack."
  },
  {
    id: "r2",
    name: "Tesla Model S Plaid",
    brand: "Tesla",
    category: "Electric",
    rating: 4.85,
    reviewsCount: 98,
    seats: 5,
    fuel: "Electric",
    transmission: "Automatic",
    pricePerDay: 32000,
    images: [
      "https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&w=800&q=80",
      // "https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=800&q=80",
      // "https://images.unsplash.com/photo-1571127236794-81c0bbfe1ce3?auto=format&fit=crop&w=800&q=80"
    ],
    features: ["Autopilot", "17\" Cinema Display", "Tri-Motor AWD", "Panoromic Roof", "Ventilated Seats", "Gaming Computer"],
    engine: "Tri-Motor Electric",
    power: "1,020 HP",
    acceleration: "1.99s (0-60 mph)",
    description: "Step into the future of motoring with the Tesla Model S Plaid. Accelerating from 0 to 60 mph in less than 2 seconds, this tri-motor electric powerhouse redefines performance, luxury, and automated driving comfort."
  },
  {
    id: "r3",
    name: "BMW M4 Competition",
    brand: "BMW",
    category: "Sports",
    rating: 4.92,
    reviewsCount: 110,
    seats: 4,
    fuel: "Petrol",
    transmission: "Automatic",
    pricePerDay: 38000,
    images: [
      "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=800&q=80",
      // "https://images.unsplash.com/photo-1607853202273-797f1c22a38e?auto=format&fit=crop&w=800&q=80",
      // "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=800&q=80"
    ],
    features: ["M Sport Exhaust", "Carbon Fiber Trim", "Heads-Up Display", "Harmon Kardon Sound", "Drift Analyzer", "Track Mode"],
    engine: "3.0L Twin-Turbo Inline-6",
    power: "503 HP",
    acceleration: "3.4s (0-60 mph)",
    description: "The BMW M4 Competition Coupe is a high-performance athlete for the road. Its precise handling, aggressive twin-turbo inline-six, and customizable M settings give you absolute control over your driving dynamics."
  },
  {
    id: "r4",
    name: "Mercedes-AMG GT Roadster",
    brand: "Mercedes",
    category: "Convertible",
    rating: 4.95,
    reviewsCount: 76,
    seats: 2,
    fuel: "Petrol",
    transmission: "Automatic",
    pricePerDay: 65000,
    images: [
      "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=800&q=80",
      // "https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=800&q=80",
      // "https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=800&q=80"
    ],
    features: ["Burmester Surround Sound", "AMG Ride Control", "Active Aerodynamics", "Nappa Leather", "Airscarf Neck Heating", "AMG Track Pace"],
    engine: "4.0L Twin-Turbo V8",
    power: "523 HP",
    acceleration: "3.7s (0-60 mph)",
    description: "With its long hood, muscular rear end, and open-top convertible design, the Mercedes-AMG GT Roadster offers a thrilling combination of sensory experiences. Powered by a handcrafted AMG V8 engine."
  },
  {
    id: "r5",
    name: "Lamborghini Huracan Evo",
    brand: "Lamborghini",
    category: "Supercar",
    rating: 4.98,
    reviewsCount: 54,
    seats: 2,
    fuel: "Petrol",
    transmission: "Automatic",
    pricePerDay: 90000,
    images: [
      "https://images.unsplash.com/photo-1621135802920-133df287f89c?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=800&q=80"
    ],
    features: ["LDVI System", "Carbon Ceramic Brakes", "Lamborghini Sensonum Audio", "Alcantara Interior", "Lifting System", "Sport Mode Exhaust"],
    engine: "5.2L Naturally Aspirated V10",
    power: "631 HP",
    acceleration: "2.9s (0-60 mph)",
    description: "The Huracán EVO is the evolution of the most successful V10-powered Lamborghini. The howling naturally aspirated V10 exhaust note combined with advanced driving dynamics control produces an unforgettable drive."
  },
  {
    id: "r6",
    name: "Audi R8 V10 Decennium",
    brand: "Audi",
    category: "Supercar",
    rating: 4.88,
    reviewsCount: 84,
    seats: 2,
    fuel: "Petrol",
    transmission: "Automatic",
    pricePerDay: 75000,
    images: [
      "https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1617531653332-bd46c24f2068?auto=format&fit=crop&w=800&q=80"
    ],
    features: ["Quattro AWD", "Virtual Cockpit", "Bang & Olufsen Audio", "Carbon Fiber Wings", "Laser Headlights", "Magnetic Ride Control"],
    engine: "5.2L FSI V10",
    power: "602 HP",
    acceleration: "3.1s (0-60 mph)",
    description: "Audi's crown jewel, the R8 V10 Decennium, represents the pinnacle of daily-drivable supercar engineering. Pairing the incredible V10 engine with legendary Quattro all-wheel drive stability."
  },
  {
    id: "r7",
    name: "Range Rover Sport SVR",
    brand: "Land Rover",
    category: "SUV",
    rating: 4.79,
    reviewsCount: 165,
    seats: 5,
    fuel: "Petrol",
    transmission: "Automatic",
    pricePerDay: 35000,
    images: [
      "https://images.unsplash.com/photo-1725815761064-b84c3f4f9b94?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8cmFuZ2UlMjByb3ZlcnxlbnwwfHwwfHx8MA%3D%3D3wxMjA3fDB8MHxzZWFyY2h8M3x8cmFuZ2UlMjByb3ZlcnxlbnwwfHwwfHx8MA%3D%3D",
      
    ],
    features: ["Supercharged Exhaust", "Panoromic Sunroof", "Meridian Signature Sound", "Aesthetic Ambient Lighting", "Air Suspension", "Terrain Response 2"],
    engine: "5.0L Supercharged V8",
    power: "575 HP",
    acceleration: "4.3s (0-60 mph)",
    description: "The Range Rover Sport SVR takes performance to new heights. Combining absolute luxury with the raw muscle of a supercharged V8 and top-tier off-roading capability, it rules both road and track."
  },
  {
    id: "r8",
    name: "Porsche Taycan Turbo S",
    brand: "Porsche",
    category: "Electric",
    rating: 4.93,
    reviewsCount: 67,
    seats: 4,
    fuel: "Electric",
    transmission: "Automatic",
    pricePerDay: 48000,
    images: [
      "https://images.unsplash.com/photo-1757366762496-45e97e68a299?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MzF8fFBvcnNjaGUlMjBUYXljYW4lMjBUdXJibyUyMFN8ZW58MHx8MHx8fDA%3D",
      // "https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?auto=format&fit=crop&w=800&q=80",
      // "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=800&q=80"
    ],
    features: ["Dual-Motor AWD", "Performance Battery Plus", "Burmester High-End Sound", "Matrix LED Headlights", "Porsche Electric Sport Sound", "Four-Zone Climate"],
    engine: "Dual Electric Motors",
    power: "750 HP",
    acceleration: "2.6s (0-60 mph)",
    description: "An electric sports car that drives like a true Porsche. The Taycan Turbo S delivers blistering acceleration, premium German luxury, and advanced 800V fast-charging system."
  },
  {
    id: "r9",
    name: "Mercedes-Benz G63 AMG",
    brand: "Mercedes",
    category: "SUV",
    rating: 4.96,
    reviewsCount: 184,
    seats: 5,
    fuel: "Petrol",
    transmission: "Automatic",
    pricePerDay: 70000,
    images: [
      "https://images.unsplash.com/photo-1648413653877-ade5eefd2f1b?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8TWVyY2VkZXMtQmVueiUyMEc2MyUyMEFNR3xlbnwwfHwwfHx8MA%3D%3D",
      
    ],
    features: ["Burmester Surround Sound", "Dual Side-Pipe Exhaust", "Designo Leather", "Triple Lock Differentials", "Massage Seats", "AMG Night Package"],
    engine: "4.0L Twin-Turbo V8",
    power: "577 HP",
    acceleration: "4.5s (0-60 mph)",
    description: "The legendary G-Wagon in its highest performance form. The G63 AMG combines standard military-grade ruggedness with premium luxury materials and a roaring twin-turbo AMG V8."
  },
  {
    id: "r10",
    name: "Audi e-tron GT",
    brand: "Audi",
    category: "Electric",
    rating: 4.82,
    reviewsCount: 71,
    seats: 5,
    fuel: "Electric",
    transmission: "Automatic",
    pricePerDay: 28000,
    images: [
      
      "https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?auto=format&fit=crop&w=800&q=80",
      
    ],
    features: ["Quattro AWD", "Bang & Olufsen Audio", "Head-Up Display", "Heated Steering Wheel", "Carbon Fiber Roof", "360 Camera System"],
    engine: "Dual Electric Motors",
    power: "522 HP",
    acceleration: "3.9s (0-60 mph)",
    description: "The Audi e-tron GT is a grand tourer that pairs cutting-edge electric performance with an expressive sculptural design. A true masterpiece of modern visual design and comfort."
  },
  {
    id: "r11",
    name: "BMW M8 Gran Coupe",
    brand: "BMW",
    category: "Luxury",
    rating: 4.9,
    reviewsCount: 62,
    seats: 5,
    fuel: "Petrol",
    transmission: "Automatic",
    pricePerDay: 42000,
    images: [
      "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=800&q=80",
      
    ],
    features: ["M xDrive AWD", "Carbon Roof", "Laserlights", "Merino Leather", "Ventilated Seats", "Alcantara Headliner"],
    engine: "4.4L Twin-Turbo V8",
    power: "617 HP",
    acceleration: "3.0s (0-60 mph)",
    description: "Four-door practicality meets raw supercar muscle. The BMW M8 Competition Gran Coupe is luxury cruising refined for the absolute speed enthusiast."
  },
  {
    id: "r12",
    name: "Tesla Model Y Performance",
    brand: "Tesla",
    category: "Electric",
    rating: 4.78,
    reviewsCount: 212,
    seats: 5,
    fuel: "Electric",
    transmission: "Automatic",
    pricePerDay: 18000,
    images: [
      "https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&w=800&q=80",
      
    ],
    features: ["Autopilot", "15\" Touchscreen", "Dual Motor AWD", "Plaid Brake Calipers", "Foldable Seats", "Supercharger Network"],
    engine: "Dual Electric Motor",
    power: "456 HP",
    acceleration: "3.5s (0-60 mph)",
    description: "The Model Y Performance offers the capability of a compact SUV with sports car performance, and has plenty of room to carry passengers and luggage on road trips."
  },
  {
    id: "r13",
    name: "Chevrolet Corvette C8",
    brand: "Chevrolet",
    category: "Sports",
    rating: 4.91,
    reviewsCount: 119,
    seats: 2,
    fuel: "Petrol",
    transmission: "Automatic",
    pricePerDay: 30000,
    images: [
      "https://images.unsplash.com/photo-1584345604476-8ec5e12e42dd?auto=format&fit=crop&w=800&q=80",
      
    ],
    features: ["Mid-Engine Layout", "Bose Premium Audio", "Removable Roof Panel", "Performance Data Recorder", "Drive Mode Selector", "Nappa Leather"],
    engine: "6.2L LT2 V8",
    power: "495 HP",
    acceleration: "2.9s (0-60 mph)",
    description: "The Corvette Stingray is a masterpiece of mid-engine engineering, bringing supercar levels of performance and a luxury fighter-jet inspired cockpit to the streets."
  },
  {
    id: "r14",
    name: "Ford Mustang Shelby GT500",
    brand: "Ford",
    category: "Muscle",
    rating: 4.87,
    reviewsCount: 93,
    seats: 4,
    fuel: "Petrol",
    transmission: "Automatic",
    pricePerDay: 25000,
    images: [
      "https://images.unsplash.com/photo-1588127333419-b9d7de223dcf?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8Rm9yZCUyME11c3RhbmclMjBTaGVsYnklMjBHVDUwMHxlbnwwfHwwfHx8MA%3D%3D",
      
    ],
    features: ["Supercharger Whine", "MagneRide Damping", "Recaro Seats", "Brembo 6-Piston Brakes", "Carbon Fiber Track Wing", "Line Lock Mode"],
    engine: "5.2L Supercharged V8",
    power: "760 HP",
    acceleration: "3.3s (0-60 mph)",
    description: "The most powerful street-legal Ford ever. The Shelby GT500 pairs a supercharged V8 with a dual-clutch transmission to dominate drag strips and canyon runs alike."
  },
  {
    id: "r15",
    name: "Jeep Wrangler Rubicon 392",
    brand: "Jeep",
    category: "Offroad",
    rating: 4.89,
    reviewsCount: 125,
    seats: 5,
    fuel: "Petrol",
    transmission: "Automatic",
    pricePerDay: 15000,
    images: [
      "https://images.unsplash.com/photo-1677318159209-86ee88e9c5ed?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8SmVlcCUyMFdyYW5nbGVyJTIwUnViaWNvbiUyMDM5MnxlbnwwfHwwfHx8MA%3D%3D",
      
    ],
    features: ["35-inch Tires", "Dual-Mode Exhaust", "Electronic Swaybar Disconnect", "Fox Shocks", "Removable Doors/Roof", "Leather Seats"],
    engine: "6.4L HEMI V8",
    power: "470 HP",
    acceleration: "4.5s (0-60 mph)",
    description: "A V8 engine in a Wrangler. The Rubicon 392 gives you incredible straight-line speed coupled with unmatched off-road capability and high water-fording clearance."
  },
  {
    id: "r16",
    name: "Aston Martin Vantage",
    brand: "Aston Martin",
    category: "Sports",
    rating: 4.92,
    reviewsCount: 41,
    seats: 2,
    fuel: "Petrol",
    transmission: "Automatic",
    pricePerDay: 60000,
    images: [
      "https://images.unsplash.com/photo-1730365646174-5cd3d9136dd0?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTV8fEFzdG9uJTIwTWFydGluJTIwVmFudGFnZXxlbnwwfHwwfHx8MA%3D%3D",
     
    ],
    features: ["Signature Front Grille", "Alcantara/Leather Trim", "Aston Martin Audio", "Active Exhaust", "Carbon Fiber Splitter", "Heated Seats"],
    engine: "4.0L Twin-Turbo V8",
    power: "503 HP",
    acceleration: "3.6s (0-60 mph)",
    description: "A beautiful British sports car with a muscular German twin-turbo heart. The Vantage is designed for absolute sensory immersion and dynamic driver response."
  },
  {
    id: "r17",
    name: "Lexus LC 500 Coupe",
    brand: "Lexus",
    category: "Luxury",
    rating: 4.86,
    reviewsCount: 59,
    seats: 4,
    fuel: "Petrol",
    transmission: "Automatic",
    pricePerDay: 20000,
    images: [
      "https://images.unsplash.com/photo-1662500038326-55ab4cc8aeda?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8TGV4dXMlMjBMQyUyMDUwMCUyMENvdXBlfGVufDB8fDB8fHww",
      
    ],
    features: ["Mark Levinson Audio", "Naturally Aspirated V8", "LFA-Style Gauges", "Alcantara Doors", "Pre-Collision System", "Active Rear Spoiler"],
    engine: "5.0L Naturally Aspirated V8",
    power: "471 HP",
    acceleration: "4.4s (0-60 mph)",
    description: "The Lexus LC 500 is a gorgeous GT car. Its screaming naturally aspirated V8 provides a mechanical soundtrack that is completely unique in the modern turbo era."
  },
  {
    id: "r18",
    name: "Maserati Ghibli Trofeo",
    brand: "Maserati",
    category: "Luxury",
    rating: 4.74,
    reviewsCount: 33,
    seats: 5,
    fuel: "Petrol",
    transmission: "Automatic",
    pricePerDay: 22000,
    images: [
      "https://images.unsplash.com/photo-1710384929737-3b1bff44f6f8?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8TWFzZXJhdGklMjBHaGlibGklMjBUcm9mZW98ZW58MHx8MHx8fDA%3D",

    ],
    features: ["Ferrari-Built Engine", "Corsa Performance Mode", "Carbon Trim", "Harman Kardon Audio", "Adaptive Suspensions", "Italian Leather Accent"],
    engine: "3.8L Twin-Turbo V8",
    power: "580 HP",
    acceleration: "4.0s (0-60 mph)",
    description: "Powered by a Ferrari-assembled twin-turbo V8, the Ghibli Trofeo infuses Maserati’s classic executive luxury with Italian supercar soul and racing genetics."
  },
  {
    id: "r19",
    name: "Audi RS6 Avant",
    brand: "Audi",
    category: "Wagon",
    rating: 4.97,
    reviewsCount: 153,
    seats: 5,
    fuel: "Petrol",
    transmission: "Automatic",
    pricePerDay: 45000,
    images: [
      "https://images.unsplash.com/photo-1655126673689-d9d0eac9c80e?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8QXVkaSUyMFJTNiUyMEF2YW50fGVufDB8fDB8fHww",
      
    ],
    features: ["Quattro AWD", "Widebody Styling", "Dynamic Ride Control", "Massive Trunk Space", "Heads-Up Display", "Rear-Wheel Steering"],
    engine: "4.0L Twin-Turbo V8",
    power: "591 HP",
    acceleration: "3.5s (0-60 mph)",
    description: "The ultimate hyper-wagon. The RS6 Avant offers blistering supercar pace, aggressive widebody design cues, and enough cargo capacity for a family holiday."
  },
  {
    id: "r20",
    name: "Mercedes-AMG E63 S",
    brand: "Mercedes",
    category: "Luxury",
    rating: 4.89,
    reviewsCount: 88,
    seats: 5,
    fuel: "Petrol",
    transmission: "Automatic",
    pricePerDay: 38000,
    images: [
      "https://images.unsplash.com/photo-1551836989-b4622a17a792?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8TWVyY2VkZXMtQU1HJTIwRTYzJTIwU3xlbnwwfHwwfHx8MA%3D%3D",
     
    ],
    features: ["Drift Mode AWD+", "AMG Exhaust", "Massage Seats", "64-Color Ambient Lighting", "Acoustic Comfort Package", "Dual Screens"],
    engine: "4.0L Twin-Turbo V8",
    power: "603 HP",
    acceleration: "3.0s (0-60 mph)",
    description: "The Mercedes-AMG E63 S is a business sedan with a wild soul. Press a button to activate Drift Mode and route 603 horsepower directly to the rear wheels."
  }
];

export const usedCars = [
  {
    id: "u1",
    brand: "BMW",
    model: "3 Series 330i M Sport",
    year: 2021,
    price: 4800000,
    mileage: 24000,
    fuel: "Petrol",
    transmission: "Automatic",
    images: [
      "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=800&q=80",
      
    ],
    engine: "2.0L 4-Cylinder Turbo",
    power: "255 HP",
    owners: 1,
    color: "Portimao Blue",
    description: "Immaculate condition BMW 330i M Sport with low mileage. Under factory warranty, serviced exclusively at authorized BMW dealership. Fully loaded with M Sport package, active park assist, and panoramic roof.",
    condition: "Excellent (No accidents)",
    seller: {
      name: "Alex Johnson",
      type: "Private Seller",
      rating: 4.9,
      phone: "+1 (555) 124-7890",
      email: "alex.j@drivehub.example"
    }
  },
  {
    id: "u2",
    brand: "Audi",
    model: "A5 Sportback 45 TFSI",
    year: 2020,
    price: 4200000,
    mileage: 38000,
    fuel: "Petrol",
    transmission: "Automatic",
    images: [
      "https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?auto=format&fit=crop&w=800&q=80",
      
    ],
    engine: "2.0L Turbocharged I4",
    power: "248 HP",
    owners: 2,
    color: "Daytona Gray",
    description: "Highly practical and stunning Audi A5 Sportback. Finished in Daytona Gray with premium Black Optic package. Features virtual cockpit, Quattro AWD system, and luxury Bang & Olufsen sound system.",
    condition: "Very Good",
    seller: {
      name: "Prestige Motors",
      type: "Dealer",
      rating: 4.7,
      phone: "+1 (555) 987-6543",
      email: "sales@prestigemotors.example"
    }
  },
  {
    id: "u3",
    brand: "Porsche",
    model: "Cayenne Coupe S",
    year: 2022,
    price: 13500000,
    mileage: 12500,
    fuel: "Petrol",
    transmission: "Automatic",
    images: [
      "https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80"
    ],
    engine: "2.9L Twin-Turbo V6",
    power: "434 HP",
    owners: 1,
    color: "Chalk",
    description: "Single-owner, low-mileage Cayenne Coupe S in rare Chalk paint. Clean Carfax, garaged indoors. Features 21-inch RS Spyder design wheels, premium package plus, active air suspension, and sport chrono package.",
    condition: "Like New",
    seller: {
      name: "Marcus Sterling",
      type: "Private Seller",
      rating: 5.0,
      phone: "+1 (555) 345-6789",
      email: "m.sterling@drivehub.example"
    }
  },
  {
    id: "u4",
    brand: "Tesla",
    model: "Model 3 Long Range",
    year: 2021,
    price: 4000000,
    mileage: 42000,
    fuel: "Electric",
    transmission: "Automatic",
    images: [
      "https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&w=800&q=80",
      
    ],
    engine: "Dual Motor Electric",
    power: "425 HP",
    owners: 1,
    color: "Pearl White Multi-Coat",
    description: "Dual-motor AWD Tesla Model 3 Long Range with full self-driving capability (FSD package paid in full). Premium interior with heated front & rear seats, battery healthy with 94% capacity retention.",
    condition: "Excellent",
    seller: {
      name: "Sophia Martinez",
      type: "Private Seller",
      rating: 4.85,
      phone: "+1 (555) 234-5678",
      email: "smartinez@drivehub.example"
    }
  },
  {
    id: "u5",
    brand: "Mercedes",
    model: "C-Class C300 Coupe",
    year: 2019,
    price: 5500000,
    mileage: 51000,
    fuel: "Petrol",
    transmission: "Automatic",
    images: [
      
      "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=800&q=80"
    ],
    engine: "2.0L Turbo Inline-4",
    power: "255 HP",
    owners: 2,
    color: "Polar White",
    description: "Stunning C300 Coupe with AMG line exterior pack. Well-maintained and recently detailed. Features panoramic roof, blind-spot monitoring, premium ambient lighting, and Apple CarPlay support.",
    condition: "Very Good",
    seller: {
      name: "Star Auto Brokers",
      type: "Dealer",
      rating: 4.6,
      phone: "+1 (555) 789-0123",
      email: "sales@starauto.example"
    }
  },
  {
    id: "u6",
    brand: "Porsche",
    model: "718 Cayman GT4",
    year: 2021,
    price: 15500000,
    mileage: 6800,
    fuel: "Petrol",
    transmission: "Manual",
    images: [
      "https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?auto=format&fit=crop&w=800&q=80",
      
    ],
    engine: "4.0L Naturally Aspirated Flat-6",
    power: "414 HP",
    owners: 1,
    color: "Guards Red",
    description: "Extremely rare Cayman GT4 with manual gearbox. Pure driver's car. Equipped with carbon fiber full bucket seats, Chrono package, and satin black wheels. Paint protection film (PPF) applied to entire front bumper/hood.",
    condition: "Mint",
    seller: {
      name: "Exotic Drive Group",
      type: "Dealer",
      rating: 4.95,
      phone: "+1 (555) 432-1098",
      email: "exotics@drivegroup.example"
    }
  },
  // Adding remaining 24 entries with varied prices, models, years, and mileages
  {
    id: "u7",
    brand: "BMW",
    model: "X5 xDrive40i M Sport",
    year: 2021,
    price: 7500000,
    mileage: 31000,
    fuel: "Petrol",
    transmission: "Automatic",
    images: ["https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=800&q=80"],
    engine: "3.0L Turbo Inline-6",
    power: "335 HP",
    owners: 1,
    color: "Mineral White",
    description: "Spacious luxury SUV, loaded with premium features. Features driving assistance professional package, parking assistance package, and sky lounge panoramic roof.",
    condition: "Excellent",
    seller: { name: "David Miller", type: "Private Seller", rating: 4.8, phone: "+1 (555) 876-5432", email: "d.miller@drivehub.example" }
  },
  {
    id: "u8",
    brand: "Mercedes",
    model: "E-Class E450 Sedan",
    year: 2020,
    price: 6800000,
    mileage: 35000,
    fuel: "Petrol",
    transmission: "Automatic",
    images: ["https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=800&q=80"],
    engine: "3.0L Twin-Turbo V6",
    power: "362 HP",
    owners: 2,
    color: "Obsidian Black",
    description: "Highly refined executive sedan with 4MATIC AWD. Features luxury cabin styling, dual display screens, adaptive cruise control, and leather seats.",
    condition: "Very Good",
    seller: { name: "Capital City Auto", type: "Dealer", rating: 4.5, phone: "+1 (555) 765-4321", email: "contact@capitalauto.example" }
  },
  {
    id: "u9",
    brand: "Audi",
    model: "Q8 55 TFSI Prestige",
    year: 2021,
    price: 9500000,
    mileage: 26500,
    fuel: "Petrol",
    transmission: "Automatic",
    images: ["https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?auto=format&fit=crop&w=800&q=80"],
    engine: "3.0L Turbocharged V6",
    power: "335 HP",
    owners: 1,
    color: "Orca Black Metallic",
    description: "Flagship Audi coupe-SUV with top Prestige trim level. Bang & Olufsen luxury audio, virtual cockpit, soft close doors, and standard matrix LED headlights.",
    condition: "Excellent",
    seller: { name: "Prestige Motors", type: "Dealer", rating: 4.7, phone: "+1 (555) 987-6543", email: "sales@prestigemotors.example" }
  },
  {
    id: "u10",
    brand: "Tesla",
    model: "Model Y Long Range",
    year: 2022,
    price: 5200000,
    mileage: 18000,
    fuel: "Electric",
    transmission: "Automatic",
    images: ["https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&w=800&q=80"],
    engine: "Dual Motor Electric",
    power: "384 HP",
    owners: 1,
    color: "Midnight Silver Metallic",
    description: "Clean title Tesla Model Y. Equipped with 20-inch Induction wheels, Autopilot, and factory tow package. Fast charging compatible, excellent battery health.",
    condition: "Like New",
    seller: { name: "Lisa Wong", type: "Private Seller", rating: 4.9, phone: "+1 (555) 654-3210", email: "l.wong@drivehub.example" }
  },
  {
    id: "u11",
    brand: "Honda",
    model: "Civic Type R",
    year: 2019,
    price: 4100000,
    mileage: 45000,
    fuel: "Petrol",
    transmission: "Manual",
    images: ["https://images.unsplash.com/photo-1686074449582-6374eaebacf3?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Q2l2aWMlMjBUeXBlJTIwUnxlbnwwfHwwfHx8MA%3D%3D"],
    engine: "2.0L Turbocharged I4",
    power: "306 HP",
    owners: 2,
    color: "Championship White",
    description: "Unmodified Civic Type R in iconic Championship White. Enthusiast owned, daily driven, oil changes every 4000 miles. Features bucket seats, manual transmission.",
    condition: "Very Good",
    seller: { name: "Ryan Davies", type: "Private Seller", rating: 4.8, phone: "+1 (555) 543-2109", email: "r.davies@drivehub.example" }
  },
  {
    id: "u12",
    brand: "Ford",
    model: "Mustang GT Premium",
    year: 2020,
    price: 4500000,
    mileage: 28000,
    fuel: "Petrol",
    transmission: "Manual",
    images: ["https://images.unsplash.com/photo-1655628266959-12ec3f839a46?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8Zm9yZCUyMG11c3RhbmclMjBndHxlbnwwfHwwfHx8MA%3D%3D"],
    engine: "5.0L Coyote V8",
    power: "460 HP",
    owners: 1,
    color: "Shadow Black",
    description: "Loud and fast Mustang GT with 6-speed manual and active valve exhaust. Features luxury leather cooling/heating seats, digital dash screen cluster.",
    condition: "Excellent",
    seller: { name: "Apex Sportscars", type: "Dealer", rating: 4.75, phone: "+1 (555) 456-7890", email: "info@apexsports.example" }
  },
  {
    id: "u13",
    brand: "Toyota",
    model: "RAV4 Hybrid Limited",
    year: 2021,
    price: 3800000,
    mileage: 33500,
    fuel: "Hybrid",
    transmission: "Automatic",
    images: ["https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=800&q=80"],
    engine: "2.5L Hybrid 4-Cylinder",
    power: "219 HP",
    owners: 1,
    color: "Silver Sky Metallic",
    description: "Highly reliable RAV4 Hybrid in the top-tier Limited trim. Offers fantastic fuel efficiency (40 mpg), all-wheel drive stability, and JBL speaker sound system.",
    condition: "Excellent",
    seller: { name: "Midwest Toyota Traders", type: "Dealer", rating: 4.4, phone: "+1 (555) 345-1234", email: "sales@midwesttoyota.example" }
  },
  {
    id: "u14",
    brand: "Defender",
    model: "Range Rover Defender 110 SE",
    year: 2020,
    price: 6200000,
    mileage: 39000,
    fuel: "Petrol",
    transmission: "Automatic",
    images: ["https://images.unsplash.com/photo-1722786102904-c6bf6bec8fc3?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8ZGVmZW5kZXIlMjAxMTB8ZW58MHx8MHx8fDA%3D"],
    engine: "3.0L Supercharged V6",
    power: "340 HP",
    owners: 2,
    color: "Byron Blue",
    description: "Fabulous styling and modern luxury. Features dual touchscreens, panoramic glass roof, active lane keep assist, and luxury Meridian surround sound.",
    condition: "Very Good",
    seller: { name: "Sterling Land Motors", type: "Dealer", rating: 4.8, phone: "+1 (555) 234-9876", email: "sales@sterlingland.example" }
  },
  {
    id: "u15",
    brand: "Lexus",
    model: "RX 350 F Sport",
    year: 2021,
    price: 5800000,
    mileage: 29000,
    fuel: "Petrol",
    transmission: "Automatic",
    images: ["https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=800&q=80"],
    engine: "3.5L V6",
    power: "295 HP",
    owners: 1,
    color: "Ultra White",
    description: "Sleek and dependable luxury SUV in white over red interior. Features standard F Sport styling bumpers, sport tuned suspension, and navigation package.",
    condition: "Excellent",
    seller: { name: "Thomas Brady", type: "Private Seller", rating: 4.9, phone: "+1 (555) 901-2345", email: "t.brady@drivehub.example" }
  },
  {
    id: "u16",
    brand: "Subaru",
    model: "WRX STI Limited",
    year: 2020,
    price: 4500000,
    mileage: 32000,
    fuel: "Petrol",
    transmission: "Manual",
    images: ["https://images.unsplash.com/photo-1773384654741-cbb48b21363f?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fFdSWCUyMFNUSSUyMExpbWl0ZWR8ZW58MHx8MHx8fDA%3D"],
    engine: "2.5L Turbocharged Boxer-4",
    power: "310 HP",
    owners: 1,
    color: "WR Blue Pearl",
    description: "Classic rally-inspired performance sedan. Features legendary symmetrical AWD, Recaro racing seats, Brembo brakes, and large STI high-profile rear spoiler.",
    condition: "Very Good",
    seller: { name: "Apex Sportscars", type: "Dealer", rating: 4.75, phone: "+1 (555) 456-7890", email: "info@apexsports.example" }
  },
  {
    id: "u17",
    brand: "Jeep",
    model: "Grand Cherokee Summit",
    year: 2019,
    price: 3900000,
    mileage: 48000,
    fuel: "Petrol",
    transmission: "Automatic",
    images: ["https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=800&q=80"],
    engine: "3.6L V6 Pentastar",
    power: "295 HP",
    owners: 2,
    color: "Granite Crystal",
    description: "Fully loaded off-road luxury SUV. Features premium signature leather interior, active air suspension, panoramic roof, and adaptive cruise control.",
    condition: "Very Good",
    seller: { name: "Midwest Auto Direct", type: "Dealer", rating: 4.3, phone: "+1 (555) 890-1234", email: "sales@midwestauto.example" }
  },
  {
    id: "u18",
    brand: "Volkswagen",
    model: "Golf R",
    year: 2019,
    price: 3700000,
    mileage: 52000,
    fuel: "Petrol",
    transmission: "Automatic",
    images: ["https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?auto=format&fit=crop&w=800&q=80"],
    engine: "2.0L Turbocharged I4",
    power: "288 HP",
    owners: 2,
    color: "Lapiz Blue Metallic",
    description: "Highly versatile hot hatch with 4Motion AWD and DSG dual-clutch transmission. Features DCC adaptive dampers, digital cockpit, and leather interior.",
    condition: "Very Good",
    seller: { name: "Eric Hansen", type: "Private Seller", rating: 4.7, phone: "+1 (555) 789-3456", email: "e.hansen@drivehub.example" }
  },
  {
    id: "u19",
    brand: "Chevrolet",
    model: "Camaro SS 1LE",
    year: 2021,
    price: 5500000,
    mileage: 15000,
    fuel: "Petrol",
    transmission: "Manual",
    images: ["https://images.unsplash.com/photo-1562911791-c7a97b729ec5?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8Q2FtYXJvJTIwU1MlMjAxTEV8ZW58MHx8MHx8fDA%3D"],
    engine: "6.2L V8",
    power: "455 HP",
    owners: 1,
    color: "Rapid Blue",
    description: "Track-ready Camaro SS with 1LE track performance package. Satin black wrapped hood, Recaro seats, active rev-matching manual shift, and magnetic ride shocks.",
    condition: "Excellent",
    seller: { name: "Apex Sportscars", type: "Dealer", rating: 4.75, phone: "+1 (555) 456-7890", email: "info@apexsports.example" }
  },
  {
    id: "u20",
    brand: "Lamborghini",
    model: "Urus V8 BiTurbo",
    year: 2019,
    price: 35000000,
    mileage: 29000,
    fuel: "Petrol",
    transmission: "Automatic",
    images: ["https://images.unsplash.com/photo-1621135802920-133df287f89c?auto=format&fit=crop&w=800&q=80"],
    engine: "4.0L Twin-Turbo V8",
    power: "641 HP",
    owners: 2,
    color: "Giallo Auge",
    description: "The world's first super utility vehicle. Striking yellow exterior with black accents. Fitted with 23-inch Taigete wheels, carbon-ceramic brakes, and ADAS driving pack.",
    condition: "Excellent",
    seller: { name: "Exotic Drive Group", type: "Dealer", rating: 4.95, phone: "+1 (555) 432-1098", email: "exotics@drivegroup.example" }
  },
  {
    id: "u21",
    brand: "Volvo",
    model: "XC90 T8 Inscription",
    year: 2020,
    price: 6000000,
    mileage: 39500,
    fuel: "Hybrid",
    transmission: "Automatic",
    images: ["https://images.unsplash.com/photo-1629897048514-3dd7414fe72a?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8dm9sdm98ZW58MHx8MHx8fDA%3D"],
    engine: "2.0L Turbo & Supercharged Hybrid",
    power: "400 HP",
    owners: 1,
    color: "Crystal White",
    description: "Three-row Swedish luxury plug-in hybrid SUV. Seats 7. Equipped with Bowers & Wilkins premium sound, Orrefors crystal gear shifter, and pilot assist driving pack.",
    condition: "Excellent",
    seller: { name: "Volvo Certified Center", type: "Dealer", rating: 4.7, phone: "+1 (555) 123-5678", email: "sales@certifiedvolvo.example" }
  },
  {
    id: "u22",
    brand: "Tesla",
    model: "Model S Long Range Plus",
    year: 2020,
    price: 6500000,
    mileage: 36000,
    fuel: "Electric",
    transmission: "Automatic",
    images: ["https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&w=800&q=80"],
    engine: "Dual Motor Electric",
    power: "562 HP",
    owners: 1,
    color: "Solid Black",
    description: "Model S LR+ with 402 miles EPA range. Free lifetime supercharging (transferable to new owner!). Autopilot, premium sound, adaptive air suspension system.",
    condition: "Excellent",
    seller: { name: "Karen Davis", type: "Private Seller", rating: 4.8, phone: "+1 (555) 987-1234", email: "k.davis@drivehub.example" }
  },
  {
    id: "u23",
    brand: "BMW",
    model: "M5 Competition LCI",
    year: 2021,
    price: 11000000,
    mileage: 18500,
    fuel: "Petrol",
    transmission: "Automatic",
    images: ["https://images.unsplash.com/flagged/photo-1553505192-acca7d4509be?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fGJtdyUyMG01fGVufDB8fDB8fHww"],
    engine: "4.4L Twin-Turbo V8",
    power: "617 HP",
    owners: 1,
    color: "Brands Hatch Grey",
    description: "Staggeringly fast executive super sedan. Active M xDrive system, Bowers & Wilkins diamonds surround system, carbon ceramic brakes, adaptive dampers.",
    condition: "Mint",
    seller: { name: "Marcus Sterling", type: "Private Seller", rating: 5.0, phone: "+1 (555) 345-6789", email: "m.sterling@drivehub.example" }
  },
  {
    id: "u24",
    brand: "Porsche",
    model: "Taycan 4S",
    year: 2020,
    price: 9000000,
    mileage: 27000,
    fuel: "Electric",
    transmission: "Automatic",
    images: ["https://images.unsplash.com/photo-1668624425139-32cfa14ab349?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTN8fFRheWNhbiUyMDRTfGVufDB8fDB8fHww"],
    engine: "Dual Electric Motor",
    power: "522 HP",
    owners: 2,
    color: "Gentian Blue Metallic",
    description: "Gorgeous Taycan 4S in blue. Features Performance Battery Plus, panoramic roof, active air suspension, 20-inch Taycan Aero wheels, and dynamic cornering lights.",
    condition: "Very Good",
    seller: { name: "Exotic Drive Group", type: "Dealer", rating: 4.95, phone: "+1 (555) 432-1098", email: "exotics@drivegroup.example" }
  },
  {
    id: "u25",
    brand: "Toyota",
    model: "Supra GR 3.0 Premium",
    year: 2021,
    price: 6200000,
    mileage: 14200,
    fuel: "Petrol",
    transmission: "Automatic",
    images: ["https://images.unsplash.com/photo-1618205062886-3976f4bb8219?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8U3VwcmF8ZW58MHx8MHx8fDA%3D"],
    engine: "3.0L Turbo Inline-6",
    power: "382 HP",
    owners: 1,
    color: "Renaissance Red 2.0",
    description: "Unmodified Supra 3.0 in red. Fitted with premium carbon fiber interior accessories, heads-up display, active blind spot monitor, and Brembo front brakes.",
    condition: "Excellent",
    seller: { name: "Apex Sportscars", type: "Dealer", rating: 4.75, phone: "+1 (555) 456-7890", email: "info@apexsports.example" }
  },
  {
    id: "u26",
    brand: "Mercedes",
    model: "GLC 43 AMG Coupe",
    year: 2020,
    price: 6500000,
    mileage: 39000,
    fuel: "Petrol",
    transmission: "Automatic",
    images: ["https://images.unsplash.com/photo-1616875491585-8e2464195d5f?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8R0xDJTIwNDMlMjBBTUclMjBDb3VwZXxlbnwwfHwwfHx8MA%3D%3D"],
    engine: "3.0L Twin-Turbo V6",
    power: "385 HP",
    owners: 2,
    color: "Selenite Gray Metallic",
    description: "Coupe-styled luxury crossover with aggressive AMG styling and exhaust tuning. 4MATIC AWD, custom ambient lights, and Burmester surround speaker pack.",
    condition: "Very Good",
    seller: { name: "Prestige Motors", type: "Dealer", rating: 4.7, phone: "+1 (555) 987-6543", email: "sales@prestigemotors.example" }
  },
  {
    id: "u27",
    brand: "Mazda",
    model: "MX-5 Miata Club",
    year: 2019,
    price: 2800000,
    mileage: 44000,
    fuel: "Petrol",
    transmission: "Manual",
    images: ["https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=800&q=80"],
    engine: "2.0L 4-Cylinder",
    power: "181 HP",
    owners: 2,
    color: "Soul Red Crystal",
    description: "Classic rear-wheel-drive roadster with manual shifting. Soft top roof, Bilstein damper shock absorber kit, mechanical slip differential, and Bose speakers.",
    condition: "Very Good",
    seller: { name: "Jack Foster", type: "Private Seller", rating: 4.75, phone: "+1 (555) 231-4567", email: "j.foster@drivehub.example" }
  },
  {
    id: "u28",
    brand: "Audi",
    model: "S4 Premium Plus",
    year: 2020,
    price: 4800000,
    mileage: 37000,
    fuel: "Petrol",
    transmission: "Automatic",
    images: ["https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?auto=format&fit=crop&w=800&q=80"],
    engine: "3.0L Turbocharged V6",
    power: "349 HP",
    owners: 2,
    color: "Navarra Blue Metallic",
    description: "Sophisticated performance sedan with clean service record. virtual cockpit, active Quattro AWD, carbon interior trim, and heated messaging sport seats.",
    condition: "Very Good",
    seller: { name: "Capital City Auto", type: "Dealer", rating: 4.5, phone: "+1 (555) 765-4321", email: "contact@capitalauto.example" }
  },
  {
    id: "u29",
    brand: "Porsche",
    model: "Macan GTS",
    year: 2021,
    price: 9800000,
    mileage: 22000,
    fuel: "Petrol",
    transmission: "Automatic",
    images: ["https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?auto=format&fit=crop&w=800&q=80"],
    engine: "2.9L Twin-Turbo V6",
    power: "375 HP",
    owners: 1,
    color: "Miami Blue",
    description: "Rare Miami Blue Macan GTS. Fully loaded with sport exhaust, GTS sport interior package, 21-inch RS Spyder wheels, and Bose premium audio system.",
    condition: "Excellent",
    seller: { name: "Thomas Brady", type: "Private Seller", rating: 4.9, phone: "+1 (555) 901-2345", email: "t.brady@drivehub.example" }
  },
  {
    id: "u30",
    brand: "BMW",
    model: "i8 Coupe",
    year: 2019,
    price: 10200000,
    mileage: 21500,
    fuel: "Hybrid",
    transmission: "Automatic",
    images: ["https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=800&q=80"],
    engine: "1.5L Turbo hybrid motor",
    power: "369 HP",
    owners: 2,
    color: "Sophisto Grey with BMW i Blue",
    description: "Futuristic hybrid sports car with butterfly dihedral doors. Finished in gray with custom blue detailing. Complete dealer service records, battery in great health.",
    condition: "Excellent",
    seller: { name: "Exotic Drive Group", type: "Dealer", rating: 4.95, phone: "+1 (555) 432-1098", email: "exotics@drivegroup.example" }
  }
];

export const testimonials = [
  {
    id: "t1",
    name: "Sarah Jenkins",
    role: "Premium Renter",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80",
    comment: "Renting the Porsche 911 for my wedding anniversary was an absolute dream. The booking process was seamless, and the car was in pristine condition. Unforgettable experience!",
    rating: 5
  },
  {
    id: "t2",
    name: "David K. Chen",
    role: "Used Car Buyer",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80",
    comment: "I was hesitant about buying a used car online, but DriveHub's certified seller reports and transparent inspection data made it stress-free. Absolutely loving my Audi A5!",
    rating: 5
  },
  {
    id: "t3",
    name: "Melissa Vance",
    role: "Used Car Seller",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=200&q=80",
    comment: "Selling my C-Class on DriveHub was incredibly fast. I listed the car, received verified buyer inquiries in 2 days, and closed the sale through their secure checkout. Highly recommend!",
    rating: 5
  },
  {
    id: "t4",
    name: "Robert Downey",
    role: "Regular Renter",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80",
    comment: "DriveHub is my go-to platform for business trips. The selection of premium German sedans is unmatched, and their executive drop-off service saves me hours.",
    rating: 5
  },
  {
    id: "t5",
    name: "Emily Rodriguez",
    role: "Sports Car Enthusiast",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80",
    comment: "Unbelievable service! The Lamborghini Huracan was drop-dead gorgeous and sounded absolutely insane. The team answered all my questions within minutes.",
    rating: 5
  },
  {
    id: "t6",
    name: "James Anderson",
    role: "First-time Buyer",
    avatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=200&q=80",
    comment: "As a first-time car buyer, I was overwhelmed. DriveHub's side-by-side spec comparison tool and transparent pricing saved me weeks of research.",
    rating: 4.8
  },
  {
    id: "t7",
    name: "Amanda Watson",
    role: "SUV Renter",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80",
    comment: "We rented the Range Rover SVR for our family road trip to Colorado. Exceptional off-roading capability, clean interior, and flawless GPS navigation support.",
    rating: 5
  },
  {
    id: "t8",
    name: "Brian Patel",
    role: "EV Buyer",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=200&q=80",
    comment: "Found a great deal on a used Tesla Model Y on DriveHub. The seller was verified, communication was direct, and the transaction was smooth as butter.",
    rating: 5
  },
  {
    id: "t9",
    name: "Catherine Zeta",
    role: "Exotic Renter",
    avatar: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&w=200&q=80",
    comment: "The Aston Martin Vantage was simply spectacular. DriveHub's customer support went out of their way to customize my rental drop-off location.",
    rating: 5
  },
  {
    id: "t10",
    name: "Michael Chang",
    role: "Car Dealer Partner",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=200&q=80",
    comment: "Partnering with DriveHub has boosted our used luxury inventory turnover by 35%. Their digital listing tool and qualified lead filters are class-leading.",
    rating: 4.9
  }
];

export const brands = [
  { name: "BMW", logo: "BMW" },
  { name: "Audi", logo: "Audi" },
  { name: "Mercedes", logo: "Mercedes" },
  { name: "Porsche", logo: "Porsche" },
  { name: "Tesla", logo: "Tesla" },
  { name: "Lamborghini", logo: "Lamborghini" }
];

export const faqData = [
  {
    question: "What is required to rent a premium car from Imperial Wheels?",
    answer: "To rent a car, you must be at least 25 years old (for premium/sports categories), hold a valid driver's license with a clean driving record, and have a major credit card in your name. International drivers require a valid passport and international driving permit."
  },
  {
    question: "How does the 'Sell Used Car' process work?",
    answer: "Selling is simple: 1) Fill in your car specs and verify ownership details, 2) Set your pricing and upload high-resolution images, 3) Complete seller information, and 4) Preview and list. Interested buyers will contact you securely through our chat relay or phone numbers."
  },
  {
    question: "Does Imperial Wheels verify used car listings?",
    answer: "Yes! Every used car listed by verified dealers includes a full vehicle condition report and Carfax history check. For private listings, we offer an optional pre-purchase diagnostic report that sellers can choose to display to boost trust."
  },
  {
    question: "Are there mileage limits on rental vehicles?",
    answer: "Most of our standard rentals include 150 free miles per day. Supercars (like the Lamborghini Huracan) have a limit of 100 free miles per day. Additional mileage can be pre-purchased during booking at a discounted rate or billed post-rental."
  },
  {
    question: "Can I cancel or modify my rental reservation?",
    answer: "Yes, you can cancel your booking for a full refund up to 48 hours before your scheduled pickup time. Cancellations made between 24-48 hours will receive a 50% refund, while cancellations within 24 hours are non-refundable."
  }
];
